[target.thumbv7m-none-eabi]
# runner = "probe-run --chip STM32F103C8 --defmt"
runner = 'arm-none-eabi-gdb -x .gdbinit'

rustflags = [
    # use the Tlink.x scrip from the cortex-m-rt crate
    "-C",
    "link-arg=--nmagic",
    "-C",
    "link-arg=-Tlink.x",
    # "-C",
    # "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7m-none-eabi"

[env]
DEFMT_LOG = "trace"
